---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo npm install -g n
    sudo n 13.8.0

- name: "install node.js 13"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "install PM2 Globlly"
  npm:
    name: pm2
    global: yes